import { OAuth2Client, TokenPayload } from 'google-auth-library';
import axios from 'axios';
import prisma from '../config/db';
import { User, UserResponse } from '../models';
import { AuthService } from './auth.service';

/**
 * Google OAuth response from token exchange
 */
interface GoogleTokenResponse {
  access_token: string;
  expires_in: number;
  refresh_token?: string;
  scope: string;
  token_type: string;
  id_token: string;
}

/**
 * Google user info from People API
 */
interface GoogleUserInfo {
  id: string;
  email: string;
  name: string;
  picture?: string;
  email_verified: boolean;
  locale?: string;
}

/**
 * Login response with user and tokens
 */
interface GoogleLoginResponse {
  user: UserResponse;
  accessToken: string;
  refreshToken: string;
}

/**
 * Google OAuth Service
 *
 * Handles OAuth 2.0 authentication flow with Google:
 * 1. Generate login URL -> User clicks and grants permissions
 * 2. Handle callback -> Exchange auth code for tokens
 * 3. Get user info -> Fetch profile from Google People API
 * 4. Create or link account -> User management (new or existing)
 *
 * Security considerations:
 * - Uses authorization code flow (server-side exchange) - most secure
 * - PKCE support for mobile/SPA clients
 * - Validates token signatures before trusting claims
 * - Stores Google ID for account linking
 * - Links accounts by email for existing users
 * - Never exposes credentials in logs or error messages
 */
export class GoogleAuthService {
  /**
   * OAuth2 client instance
   * @private
   */
  private static client: OAuth2Client;

  /**
   * Base URL for Google People API
   * @private
   */
  private static readonly GOOGLE_PEOPLE_API = 'https://www.googleapis.com/oauth2/v2/userinfo';

  /**
   * Scopes requested from Google
   * - openid: Get ID token for identification
   * - profile: Get name and picture
   * - email: Get email address
   * @private
   */
  private static readonly SCOPES = ['openid', 'profile', 'email'];

  /**
   * Initialize OAuth2 client (call on service startup)
   *
   * @throws Error if required environment variables are missing
   */
  static initialize(): void {
    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
    const redirectUri = process.env.GOOGLE_REDIRECT_URI;

    if (!clientId || !clientSecret || !redirectUri) {
      throw new Error(
        'Missing required Google OAuth environment variables: ' +
        'GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI'
      );
    }

    this.client = new OAuth2Client({
      clientId,
      clientSecret,
      redirectUri,
    });
  }

  /**
   * Generate Google login URL for user to visit
   *
   * Flow:
   * 1. Generate URL with scopes and state parameter
   * 2. User visits URL and grants permissions
   * 3. Google redirects to callback with authorization code
   * 4. Backend exchanges code for tokens
   *
   * Security:
   * - State parameter prevents CSRF attacks (should be stored in session)
   * - Access type 'offline' requests refresh token for long-lived access
   * - Prompt 'select_account' lets users choose which Google account to use
   *
   * @param state - CSRF token (generated by frontend, validated on callback)
   * @returns Google OAuth login URL
   */
  static getAuthURL(state: string): string {
    if (!this.client) {
      this.initialize();
    }

    const url = this.client.generateAuthUrl({
      access_type: 'offline', // Requests refresh token for long-lived access
      scope: this.SCOPES, // Request user info scopes
      state, // CSRF protection - frontend must validate on callback
      prompt: 'select_account', // Force account selection if user has multiple Google accounts
    });

    return url;
  }

  /**
   * Exchange authorization code for OAuth tokens
   *
   * Flow (from Google):
   * 1. User grants permissions on Google consent screen
   * 2. Browser redirected to callback URL with 'code' parameter
   * 3. Backend exchanges code (+ credentials) for tokens
   * 4. Google returns access_token, refresh_token, id_token
   *
   * Security:
   * - Code is single-use and expires quickly (~10 minutes)
   * - Code exchange must include client_secret (done server-side)
   * - Never expose code to frontend
   * - ID token is JWT - signature verified by google-auth-library
   *
   * @param code - Authorization code from Google redirect
   * @returns Google tokens and basic profile info
   * @throws Error if code is invalid or exchange fails
   */
  static async handleCallback(code: string): Promise<GoogleTokenResponse & { profile: TokenPayload }> {
    if (!this.client) {
      this.initialize();
    }

    try {
      // Exchange authorization code for tokens
      // This request includes client_secret (only safe on backend)
      const { tokens } = await this.client.getToken(code);

      // Verify ID token signature and extract claims
      // ID token is a JWT with user claims
      const ticket = await this.client.verifyIdToken({
        idToken: tokens.id_token!,
        audience: process.env.GOOGLE_CLIENT_ID,
      });

      const profile = ticket.getPayload();

      if (!profile) {
        throw new Error('Failed to extract user info from ID token');
      }

      return {
        access_token: tokens.access_token!,
        expires_in: tokens.expiry_date ? Math.floor((tokens.expiry_date - Date.now()) / 1000) : 3600,
        refresh_token: tokens.refresh_token ?? undefined,
        scope: tokens.scope || this.SCOPES.join(' '),
        token_type: 'Bearer',
        id_token: tokens.id_token!,
        profile,
      };
    } catch (error) {
      if (error instanceof Error) {
        // Don't expose sensitive auth details in error messages
        throw new Error(`OAuth callback failed: ${error.message}`);
      }
      throw error;
    }
  }

  /**
   * Fetch user information from Google People API
   *
   * Retrieves full user profile from Google's authorization scopes:
   * - Basic identity (sub/id, email, name)
   * - Profile picture URL
   * - Email verification status
   *
   * Security:
   * - Requires valid access token (verifies authorization)
   * - Uses HTTPS only
   * - Can be called with refresh token to renew access token
   *
   * @param accessToken - Valid Google access token
   * @returns User info from Google
   * @throws Error if token is invalid or API call fails
   */
  static async getUserInfo(accessToken: string): Promise<GoogleUserInfo> {
    try {
      const response = await axios.get<GoogleUserInfo>(this.GOOGLE_PEOPLE_API, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });

      return response.data;
    } catch (error: any) {
      if (axios.isAxiosError(error)) {
        if (error.response?.status === 401) {
          throw new Error('Access token is invalid or expired');
        }
        throw new Error(`Failed to fetch Google user info: ${error.message}`);
      }
      throw error;
    }
  }

  /**
   * Login or create user from Google profile
   *
   * Account linking strategy:
   * 1. Check if Google ID already exists in DB (returning user)
   * 2. If not, check if email exists (user previously signed up with email)
   * 3. If email found, link Google ID to existing account (account merging)
   * 4. If neither, create new user with Google ID
   *
   * Flow:
   * - First login: Creates new user, stores Google ID
   * - Subsequent logins: Finds user by Google ID, generates new tokens
   * - Email collision: Links Google ID to existing email account
   *
   * Security:
   * - Email verified check: Only trusts email if Google verified it
   * - Returns JWT tokens for subsequent API requests
   * - Never returns Google access token to frontend
   * - Google ID is unique per Google account
   *
   * @param googleProfile - User profile from Google (ID token or People API)
   * @returns User data and JWT tokens for API access
   * @throws Error if user creation fails or data is invalid
   */
  static async loginOrCreateUser(googleProfile: TokenPayload): Promise<GoogleLoginResponse> {
    // Extract user data from Google ID token
    const googleId = googleProfile.sub; // Google's unique user ID
    const email = googleProfile.email?.toLowerCase().trim();
    const name = googleProfile.name || googleProfile.email?.split('@')[0] || 'Google User';
    const avatarUrl = googleProfile.picture || null;
    const emailVerified = googleProfile.email_verified || false;

    // Validate required fields
    if (!googleId || !email) {
      throw new Error('Google profile missing required fields: ID and email');
    }

    if (!emailVerified) {
      throw new Error('Google account email not verified');
    }

    try {
      // Strategy 1: Check if this Google ID already exists (returning user)
      let user = await prisma.user.findUnique({
        where: { googleId },
      });

      if (user) {
        // Returning user - generate new tokens
        const accessToken = AuthService.signAccessToken(user.id, user.email);
        const refreshToken = AuthService.signRefreshToken(user.id, user.email);

        return {
          user: this.userToResponse(user),
          accessToken,
          refreshToken,
        };
      }

      // Strategy 2: Check if email already exists (email signup previously)
      user = await prisma.user.findUnique({
        where: { email },
      });

      if (user) {
        // Link Google ID to existing account (account merging)
        user = await prisma.user.update({
          where: { id: user.id },
          data: {
            googleId, // Link Google ID
            avatarUrl: avatarUrl || user.avatarUrl, // Update avatar if Google has one
            updatedAt: new Date(),
          },
        });

        const accessToken = AuthService.signAccessToken(user.id, user.email);
        const refreshToken = AuthService.signRefreshToken(user.id, user.email);

        return {
          user: this.userToResponse(user),
          accessToken,
          refreshToken,
        };
      }

      // Strategy 3: New user - create account with Google ID
      user = await prisma.user.create({
        data: {
          googleId,
          email,
          name: name.trim(),
          avatarUrl,
          passwordHash: '', // OAuth users don't have passwords
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      });

      const accessToken = AuthService.signAccessToken(user.id, user.email);
      const refreshToken = AuthService.signRefreshToken(user.id, user.email);

      return {
        user: this.userToResponse(user),
        accessToken,
        refreshToken,
      };
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`Failed to process Google login: ${error.message}`);
      }
      throw error;
    }
  }

  /**
   * Complete OAuth flow: code -> tokens -> user
   *
   * Combines all steps:
   * 1. Exchange code for Google tokens
   * 2. Verify ID token
   * 3. Create or link user account
   *
   * @param code - Authorization code from Google
   * @returns User and JWT tokens
   * @throws Error if any step fails
   */
  static async completeOAuthFlow(code: string): Promise<GoogleLoginResponse> {
    // Step 1: Exchange authorization code for tokens
    const tokenResponse = await this.handleCallback(code);

    // Step 2: Extract and verify user profile from ID token
    const googleProfile = tokenResponse.profile;

    // Step 3: Create or link user, return JWT tokens
    return this.loginOrCreateUser(googleProfile);
  }

  /**
   * Refresh Google access token (if expired)
   *
   * When access token expires, use refresh token to get new one.
   * Should be called transparently by middleware if needed.
   *
   * @param refreshToken - Google refresh token
   * @returns New access token
   * @throws Error if refresh fails
   */
  static async refreshAccessToken(refreshToken: string): Promise<string> {
    if (!this.client) {
      this.initialize();
    }

    try {
      this.client.setCredentials({
        refresh_token: refreshToken,
      });

      const { credentials } = await this.client.refreshAccessToken();
      return credentials.access_token || '';
    } catch (error) {
      throw new Error('Failed to refresh Google access token');
    }
  }

  /**
   * Revoke Google access token (logout)
   *
   * Immediately revokes user's granted permissions.
   * They'll need to re-consent to login again.
   *
   * @param accessToken - Google access token to revoke
   * @returns true if revocation succeeded
   */
  static async revokeAccessToken(accessToken: string): Promise<boolean> {
    try {
      await this.client.revokeToken(accessToken);
      return true;
    } catch (error) {
      // Token might already be revoked or invalid - not critical
      console.error('Failed to revoke Google token:', error);
      return false;
    }
  }

  // Token generation delegated to AuthService.signAccessToken / signRefreshToken

  /**
   * Convert user entity to response (excludes sensitive data)
   *
   * @param user - User entity from database
   * @returns User response without password hash or sensitive fields
   * @private
   */
  private static userToResponse(user: User): UserResponse {
    return {
      id: user.id,
      email: user.email,
      name: user.name,
      avatarUrl: user.avatarUrl,
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    };
  }
}
